/* @bruin
name: lakehouse.base_model
type: duckdb.sql
connection: ducklake
description: |
  Typed base view for NYC Open Data Motor Vehicle Collisions.
  This keeps the source fields needed by downstream Bruin models.

depends:
  - nyc_open_data.motor_vehicle_collisions

materialization:
  type: view

columns:
  - name: collision_id
    type: BIGINT
    description: Unique record code generated by NYC Open Data.
    primary_key: true
    checks:
      - name: unique
      - name: not_null
  - name: crash_datetime
    type: TIMESTAMP
    description: Occurrence date of collision as a timestamp.
  - name: crash_date
    type: DATE
    description: Occurrence date of collision.
  - name: crash_time
    type: TIME
    description: Occurrence time of collision.
  - name: borough
    type: VARCHAR
    description: Borough where collision occurred.
  - name: zip_code
    type: VARCHAR
    description: Postal code of incident occurrence.
  - name: latitude
    type: DOUBLE
    description: Latitude coordinate.
  - name: longitude
    type: DOUBLE
    description: Longitude coordinate.
  - name: number_of_persons_injured
    type: INTEGER
    description: Number of persons injured.
  - name: number_of_persons_killed
    type: INTEGER
    description: Number of persons killed.

custom_checks:
  - name: base view has rows
    query: SELECT COUNT(*) > 0 FROM lakehouse.base_model
    value: 1

@bruin */

SELECT
  TRY_CAST(collision_id AS BIGINT) AS collision_id,
  TRY_CAST(crash_date AS TIMESTAMP) AS crash_datetime,
  TRY_CAST(crash_date AS DATE) AS crash_date,
  TRY_CAST(crash_time AS TIME) AS crash_time,
  CAST(on_street_name AS VARCHAR) AS on_street_name,
  CAST(off_street_name AS VARCHAR) AS off_street_name,
  CAST(cross_street_name AS VARCHAR) AS cross_street_name,
  CAST(borough AS VARCHAR) AS borough,
  CAST(zip_code AS VARCHAR) AS zip_code,
  TRY_CAST(latitude AS DOUBLE) AS latitude,
  TRY_CAST(longitude AS DOUBLE) AS longitude,
  location,
  TRY_CAST(number_of_persons_injured AS INTEGER) AS number_of_persons_injured,
  TRY_CAST(number_of_persons_killed AS INTEGER) AS number_of_persons_killed,
  TRY_CAST(number_of_pedestrians_injured AS INTEGER) AS number_of_pedestrians_injured,
  TRY_CAST(number_of_pedestrians_killed AS INTEGER) AS number_of_pedestrians_killed,
  TRY_CAST(number_of_cyclist_injured AS INTEGER) AS number_of_cyclist_injured,
  TRY_CAST(number_of_cyclist_killed AS INTEGER) AS number_of_cyclist_killed,
  TRY_CAST(number_of_motorist_injured AS INTEGER) AS number_of_motorist_injured,
  TRY_CAST(number_of_motorist_killed AS INTEGER) AS number_of_motorist_killed,
  CAST(contributing_factor_vehicle_1 AS VARCHAR) AS contributing_factor_vehicle_1,
  CAST(contributing_factor_vehicle_2 AS VARCHAR) AS contributing_factor_vehicle_2,
  CAST(contributing_factor_vehicle_3 AS VARCHAR) AS contributing_factor_vehicle_3,
  CAST(contributing_factor_vehicle_4 AS VARCHAR) AS contributing_factor_vehicle_4,
  CAST(contributing_factor_vehicle_5 AS VARCHAR) AS contributing_factor_vehicle_5,
  CAST(vehicle_type_code1 AS VARCHAR) AS vehicle_type_code1,
  CAST(vehicle_type_code2 AS VARCHAR) AS vehicle_type_code2,
  CAST(vehicle_type_code_3 AS VARCHAR) AS vehicle_type_code_3,
  CAST(vehicle_type_code_4 AS VARCHAR) AS vehicle_type_code_4,
  CAST(vehicle_type_code_5 AS VARCHAR) AS vehicle_type_code_5
FROM nyc_open_data.motor_vehicle_collisions
WHERE TRY_CAST(collision_id AS BIGINT) IS NOT NULL
QUALIFY ROW_NUMBER() OVER (
  PARTITION BY TRY_CAST(collision_id AS BIGINT)
  ORDER BY
    TRY_CAST(crash_date AS TIMESTAMP) DESC NULLS LAST,
    TRY_CAST(crash_time AS TIME) DESC NULLS LAST
) = 1
